export const AMENITIES = [
  { key: 'wifi', icon: '📶', label: 'ინტერნეტი (WiFi)' },
  { key: 'ac', icon: '❄️', label: 'კონდიციონერი' },
  { key: 'heating', icon: '🔥', label: 'გათბობა' },
  { key: 'hot_water', icon: '🚿', label: 'ცხელი წყალი' },
  { key: 'kitchen', icon: '🍳', label: 'სამზარეულო' },
  { key: 'gas', icon: '🔵', label: 'გაზი' },
  { key: 'fridge', icon: '🧊', label: 'მაცივარი' },
  { key: 'washer', icon: '🧺', label: 'სარეცხი მანქანა' },
  { key: 'tv', icon: '📺', label: 'ტელევიზორი' },
  { key: 'parking', icon: '🚗', label: 'პარკინგი' },
  { key: 'pool', icon: '🏊', label: 'საცურაო აუზი' },
  { key: 'garden', icon: '🌳', label: 'ეზო/ბაღი' },
  { key: 'bbq', icon: '🍖', label: 'მანგალი/გრილი' },
  { key: 'balcony', icon: '🌅', label: 'აივანი/ტერასა' },
  { key: 'sea_view', icon: '🌊', label: 'ზღვის ხედი' },
  { key: 'pets', icon: '🐾', label: 'შინაური ცხოველები დაშვებულია' },
  { key: 'safe', icon: '🔒', label: 'სეიფი' },
  { key: 'linens', icon: '🛏️', label: 'თეთრეული და პირსახოცები' },
];
