export const AMENITIES = [
  { key: 'wifi', icon: '📶', label: 'ინტერნეტი (WiFi)', label_en: 'Wi-Fi', label_ru: 'Wi-Fi', label_hy: 'Wi-Fi' },
  { key: 'ac', icon: '❄️', label: 'კონდიციონერი', label_en: 'Air conditioning', label_ru: 'Кондиционер', label_hy: 'Օդորակիչ' },
  { key: 'heating', icon: '🔥', label: 'გათბობა', label_en: 'Heating', label_ru: 'Отопление', label_hy: 'Ջեռուցում' },
  { key: 'hot_water', icon: '🚿', label: 'ცხელი წყალი', label_en: 'Hot water', label_ru: 'Горячая вода', label_hy: 'Տաք ջուր' },
  { key: 'kitchen', icon: '🍳', label: 'სამზარეულო', label_en: 'Kitchen', label_ru: 'Кухня', label_hy: 'Խոհանոց' },
  { key: 'gas', icon: '🔵', label: 'გაზი', label_en: 'Gas', label_ru: 'Газ', label_hy: 'Գազ' },
  { key: 'fridge', icon: '🧊', label: 'მაცივარი', label_en: 'Refrigerator', label_ru: 'Холодильник', label_hy: 'Սառնարան' },
  { key: 'washer', icon: '🧺', label: 'სარეცხი მანქანა', label_en: 'Washing machine', label_ru: 'Стиральная машина', label_hy: 'Լվացքի մեքենա' },
  { key: 'tv', icon: '📺', label: 'ტელევიზორი', label_en: 'TV', label_ru: 'Телевизор', label_hy: 'Հեռուստացույց' },
  { key: 'parking', icon: '🚗', label: 'პარკინგი', label_en: 'Parking', label_ru: 'Парковка', label_hy: 'Ավտոկայանատեղի' },
  { key: 'pool', icon: '🏊', label: 'საცურაო აუზი', label_en: 'Swimming pool', label_ru: 'Бассейн', label_hy: 'Լողավազան' },
  { key: 'garden', icon: '🌳', label: 'ეზო/ბაღი', label_en: 'Yard / garden', label_ru: 'Двор / сад', label_hy: 'Բակ/այգի' },
  { key: 'bbq', icon: '🍖', label: 'მანგალი/გრილი', label_en: 'BBQ / grill', label_ru: 'Мангал / гриль', label_hy: 'Խորոված/գրիլ' },
  { key: 'balcony', icon: '🌅', label: 'აივანი/ტერასა', label_en: 'Balcony / terrace', label_ru: 'Балкон / терраса', label_hy: 'Պատշգամբ/տեռաս' },
  { key: 'sea_view', icon: '🌊', label: 'ზღვის ხედი', label_en: 'Sea view', label_ru: 'Вид на море', label_hy: 'Ծովի տեսարան' },
  { key: 'pets', icon: '🐾', label: 'შინაური ცხოველები დაშვებულია', label_en: 'Pets allowed', label_ru: 'Можно с животными', label_hy: 'Ընտանի կենդանիներով' },
  { key: 'safe', icon: '🔒', label: 'სეიფი', label_en: 'Safe', label_ru: 'Сейф', label_hy: 'Սեյֆ' },
  { key: 'linens', icon: '🛏️', label: 'თეთრეული და პირსახოცები', label_en: 'Linens & towels', label_ru: 'Бельё и полотенца', label_hy: 'Սպիտակեղեն և սրբիչներ' },
];
